import express from 'express';
const router = express.Router();

import { handler_0 } from '../controllers/authController.js';
import { handler_1 } from '../controllers/dashboardController.js';
import { handler_2, handler_3, handler_4, handler_5 } from '../controllers/projectController.js';
import { handler_6, handler_7, handler_8, handler_9 } from '../controllers/parcelController.js';
import { handler_10, handler_11 } from '../controllers/workflowController.js';
import { handler_12, handler_13, handler_14 } from '../controllers/compensationController.js';
import { handler_15 } from '../controllers/rrController.js';
import { handler_16, handler_17 } from '../controllers/fieldSurveyController.js';
import { handler_18, handler_19 } from '../controllers/documentController.js';
import { handler_20 } from '../controllers/citizenController.js';
import { handler_21, handler_31 } from '../controllers/integrationController.js';
import { handler_22, handler_23 } from '../controllers/auditController.js';
import { handler_24, handler_25, handler_26, handler_27 } from '../controllers/grievanceController.js';
import { handler_28, handler_29, handler_30 } from '../controllers/notificationController.js';
import { translateText } from '../controllers/translationController.js';

router.post('/login', handler_0);
router.post('/auth/login', handler_0);
router.get('/analytics/dashboard', handler_1);
router.get('/projects', handler_2);
router.get('/projects/:id', handler_3);
router.post('/projects', handler_4);
router.put('/projects/:id', handler_5);
router.get('/parcels', handler_6);
router.put('/parcels/:id/status', handler_7);
router.get('/parcels/:id', handler_8);
router.post('/parcels', handler_9);
router.put('/workflow/:stageId', handler_10);
router.post('/projects/:id/approve-survey', handler_11);
router.get('/compensation', handler_12);
router.put('/compensation/:id/hold', handler_13);
router.post('/compensation/disburse', handler_14);
router.get('/rr', handler_15);
router.get('/field-surveys', handler_16);
router.post('/field-surveys', handler_17);
router.get('/documents', handler_18);
router.post('/documents', handler_19);
router.get('/citizen/my-land', handler_20);
router.get('/integrations/ulpin-check/:ulpin', handler_21);
router.get('/audit-logs', handler_22);
router.get('/audit-logs/parcel/:ulpin', handler_23);
router.post('/citizen/grievance', handler_24);
router.get('/grievances', handler_25);
router.put('/grievances/:id/resolve', handler_26);
router.put('/grievances/:id/close', handler_27);
router.get('/notifications', handler_28);
router.post('/notifications', handler_29);
router.put('/notifications/read', handler_30);
router.get('/bhu-naksha/verify/:ulpin', handler_31);
router.post('/translate', translateText);

export default router;
